sudo: false
language: node_js
node_js:
- '6'
- '7'
- '8'
- '9'
- '10'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
notifications:
  email:
    on_success: never
    on_failure: always
before_install:
- npm update
install:
- npm install
script:
- npm test